# Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Wellbeing_and_lifestyle_data_Kaggle.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[3 2 2 ... 5 '36 to 50' 1]
 [2 3 4 ... 6 '36 to 50' 1]
 [2 3 3 ... 3 '36 to 50' 1]
 ...
 [4 3 0 ... 10 '21 to 35' 0]
 [1 1 10 ... 8 '21 to 35' 1]
 [5 4 0 ... 4 '21 to 35' 1]]


In [4]:
print(y)

[609.5 655.6 631.6 ... 716.6 682.  651.4]


In [5]:
y = y.reshape(len(y),1)

In [ ]:
print(y)

[[609.5]
 [655.6]
 [631.6]
 ...
 [716.6]
 [682. ]
 [651.4]]


In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

## Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

## Training the dataset using XGBoost

In [9]:
from xgboost import XGBRegressor
regressor = XGBRegressor()
regressor.fit(X_train, y_train)

[05:24:15] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor()

## Determining accuracy
 

In [10]:
y_pred = regressor.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9825717998502534

In [11]:
t=[[5,4,0,2,10,10,5,1,2,7,4,1,5,8,5,2,2,1,8,4,'21 to 35',1]]

In [12]:
t=ct.transform(t)

In [13]:
regressor.predict(t)

array([659.2073], dtype=float32)